# Generated by Django 5.0.2 on 2024-05-08 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('license', models.FileField(upload_to='')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('biodata', models.FileField(upload_to='')),
                ('accoundnumber', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(default=1)),
                ('tprice', models.FloatField()),
                ('saddress', models.CharField(max_length=80)),
                ('sstate', models.CharField(max_length=20)),
                ('sdistrict', models.CharField(max_length=20)),
                ('spincode', models.IntegerField()),
                ('sphone', models.IntegerField()),
                ('nname', models.CharField(default='', max_length=30)),
                ('payment_mode', models.CharField(max_length=150)),
                ('payment_id', models.CharField(default=0, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for shipping', 'Out for shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('ingredients', models.CharField(max_length=300)),
                ('netquantity', models.CharField(max_length=30)),
                ('fragrance', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex'), ('Gift', 'Gift'), ('Best seller', 'Best seller')], default='Men', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('orderdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pro')),
            ],
        ),
        migrations.CreateModel(
            name='c_rt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=30)),
                ('cart_quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('delivered', models.BooleanField(default=False)),
                ('pro_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pro')),
                ('user_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('user_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register'),
        ),
        migrations.CreateModel(
            name='mbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processed', 'Order Processed'), ('Order Dispatched', 'Order Dispatched'), ('Pending', 'Pending'), ('Out for shipping', 'Out for shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order Received', max_length=100)),
                ('payment_id', models.CharField(default='COD', max_length=150)),
                ('order_id', models.CharField(max_length=150)),
                ('delivered', models.BooleanField(default=False)),
                ('item_no', models.IntegerField()),
                ('tprice', models.IntegerField()),
                ('saddress', models.CharField(max_length=80)),
                ('sstate', models.CharField(max_length=20)),
                ('sdistrict', models.CharField(max_length=20)),
                ('spincode', models.IntegerField()),
                ('sphone', models.IntegerField()),
                ('nname', models.CharField(default='', max_length=30)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.c_rt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='sbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processed', 'Order Processed'), ('Order Dispatched', 'Order Dispatched'), ('Pending', 'Pending'), ('Out for shipping', 'Out for shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order Received', max_length=100)),
                ('payment_id', models.CharField(default='COD', max_length=150)),
                ('order_id', models.CharField(max_length=150)),
                ('delivered', models.BooleanField(default=False)),
                ('quant', models.IntegerField(default=1)),
                ('tprice', models.IntegerField()),
                ('saddress', models.CharField(max_length=80)),
                ('sstate', models.CharField(max_length=20)),
                ('sdistrict', models.CharField(max_length=20)),
                ('spincode', models.IntegerField()),
                ('sphone', models.IntegerField()),
                ('nname', models.CharField(default='', max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='singlee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprice', models.FloatField()),
                ('squantity', models.IntegerField()),
                ('stotal', models.IntegerField()),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('oddr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
                ('sproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pro')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
    ]
