# Generated by Django 5.0.2 on 2024-05-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Men', max_length=100),
        ),
    ]
