# Generated by Django 5.0.2 on 2024-06-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_pro_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbooking',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='singlee',
            name='oddr',
        ),
        migrations.RemoveField(
            model_name='singlee',
            name='sproduct',
        ),
        migrations.RemoveField(
            model_name='singlee',
            name='user',
        ),
        migrations.DeleteModel(
            name='mbooking',
        ),
        migrations.DeleteModel(
            name='sbooking',
        ),
        migrations.DeleteModel(
            name='singlee',
        ),
    ]
