# Generated by Django 5.0.2 on 2024-06-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_sbooking_product_remove_sbooking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
